//---------------------------------------------------------------------------------------------
// Credits to Momentum Mod for this code and specifically xen-000
//---------------------------------------------------------------------------------------------


#ifdef _WIN32
    #pragma once
#endif
#include <cbase.h>

// You probably do not need this
#define dbging yep

#if defined (BIN_PATCHES) && defined(ENGINE_DETOURS)
#include <engine_hacks/bin_patch.h>
#include <engine_hacks/engine_detours.h>
CEngineDetours* gCEngineDetours = nullptr;

#ifdef dbging
    #define goodcolor   Color(90, 240, 90, 255) // green
    #define okcolor     Color(246, 190, 0, 255) // yellow
#endif

CBinary g_CBinary;


// This is needed so that CAutoGameSystem knows that we're using it, apparently
CBinary::CBinary() : CAutoGameSystem("")
{
}

// Bin Patch format:
//==============================
// m_pSignature:    Memory signature
// m_iSize:         Size of mem sig
// 
// m_iOffset:       Patch offset
// m_bImmediate:    Immediate or referenced variable
// m_pPatch:        Patch bytes (int/float/char*)
//==============================
// Signature mask is now autogenerated. Wildcard bytes = \x2A
// FOR THE RECORD THIS IS SDK2013 BINS NOT TF2 ONES
//
// -sappho
CBinPatch g_EnginePatches[] = 
{
    #ifdef PLATFORM_WINDOWS
        #ifdef GAME_DLL
        // Server only!
        /*
            Patch:
            Prevent clients from lagging out the server by spamming a bunch of invalid *netchan->RequestFile requests
            This lags out the server by spamming messages to console (CALL ConMsg), which is resource intensive, because of course it is
        */
        // --- PART ONE ---
        //
        // name:gigalib-patch-CNetChan::HandleUpload-win32
        // Signature for FUN_101a44e0 (32bit)
        // 55 8b ec 81 ec 1c 01 00 00 53 56 69 75 08 2c 01 00 00 8b 9d 57
        // Unique string: "Download file '%s' %s"
        // 
        // name:gigalib-patch-CNetChan::HandleUpload-win32
        // Signature for FUN_1801cc830 (64bit)
        // 48 89 5c 24 08 48 89 74 24 18 57 48 81 ec 50 01 00 00 48 63 c2 48 8d 99 68 01 00 00 48 69 d0 38 01 00 00 48 8b f1 48 03 da 48 83 bb 10 01 00 00 00 0f 84 ?? ?? ?? ?? 
        //
        // CNetChan::HandleUpload(char *, int)
#if PLATFORM_64BITS
        {
            AY_OBFUSCATE("\x48\x89\x5C\x24\x08\x48\x89\x74\x24\x18\x57\x48\x81\xEC\x50\x01\x00\x00\x48\x63\xC2\x48\x8D\x99\x68\x01\x00\x00\x48\x69\xD0\x38\x01\x00\x00\x48\x8B\xF1\x48\x03\xDA\x48\x83\xBB\x10\x01\x00\x00\x00\x0F\x84\x2A\x2A\x2A\x2A"),
            55,
            0x368,
            PATCH_IMMEDIATE,
            AY_OBFUSCATE("\x90\x90\x90\x90\x90\x90") // CALL -> NOP NOP NOP NOP NOP NOP
        },
#else
        {
            AY_OBFUSCATE("\x55\x8b\xEC\x81\xEC\x1C\x01\x00\x00\x53\x56\x69\x75\x08\x2C\x01\x00\x00\x8B\xD9\x57"),
            // AY_OBFUSCATE("\x55\x8B\xEC\xA1\x2A\x2A\x2A\x2A\x81\xEC\x04\x01\x00\x00\xA8\x01"),
            21,
            0x303, // 0x167,
            PATCH_IMMEDIATE,
            AY_OBFUSCATE("\x90\x90\x90\x90\x90\x90") // CALL -> NOP NOP NOP NOP NOP NOP
        },
#endif
        // --- PART TWO THREE FOUR AND FIVE---
        //
        // Unique string: "CreateFragmentsFromFile: '%s' doesn't"
        //
        // CNetChan::CreateFragmentsFromFile(char const*, int, unsigned int)
#if PLATFORM_64BITS
        // offsets for the ConMsgs in this func are
        // 0xBA
        // 0x100
        // 0x125
        // 0x1A0
        // 
        // name:gigalib-patch-CNetChan::CreateFragmentsFromFile-win64
        // Signature for FUN_1801cd520
        // 48 89 5c 24 08 48 89 6c 24 18 56 57 41 54 41 56 41 57 48 83 ec 20 4d 63 f8 45 8b f1 48 8b fa 48 8b e9 48 85 d2 0f 84 ?? ?? ?? ?? 80 3a 00 0f 84 ?? ?? ?? ?? 45 33 e4 4c 8d 99 28 01 00 00 41 8b f4
        {
            AY_OBFUSCATE("\x48\x89\x5C\x24\x08\x48\x89\x6C\x24\x18\x56\x57\x41\x54\x41\x56\x41\x57\x48\x83\xEC\x20\x4D\x63\xF8\x45\x8B\xF1\x48\x8B\xFA\x48\x8B\xE9\x48\x85\xD2\x0F\x84"),
            39,
            0xBA,
            PATCH_IMMEDIATE,
            AY_OBFUSCATE("\x90\x90\x90\x90\x90\x90") // CALL -> NOP NOP NOP NOP NOP NOP
        },
        {
            AY_OBFUSCATE("\x48\x89\x5C\x24\x08\x48\x89\x6C\x24\x18\x56\x57\x41\x54\x41\x56\x41\x57\x48\x83\xEC\x20\x4D\x63\xF8\x45\x8B\xF1\x48\x8B\xFA\x48\x8B\xE9\x48\x85\xD2\x0F\x84"),
            39,
            0x100,
            PATCH_IMMEDIATE,
            AY_OBFUSCATE("\x90\x90\x90\x90\x90\x90") // CALL -> NOP NOP NOP NOP NOP NOP
        },
        {
            AY_OBFUSCATE("\x48\x89\x5C\x24\x08\x48\x89\x6C\x24\x18\x56\x57\x41\x54\x41\x56\x41\x57\x48\x83\xEC\x20\x4D\x63\xF8\x45\x8B\xF1\x48\x8B\xFA\x48\x8B\xE9\x48\x85\xD2\x0F\x84"),
            39,
            0x125,
            PATCH_IMMEDIATE,
            AY_OBFUSCATE("\x90\x90\x90\x90\x90\x90") // CALL -> NOP NOP NOP NOP NOP NOP
        },
        {
            AY_OBFUSCATE("\x48\x89\x5C\x24\x08\x48\x89\x6C\x24\x18\x56\x57\x41\x54\x41\x56\x41\x57\x48\x83\xEC\x20\x4D\x63\xF8\x45\x8B\xF1\x48\x8B\xFA\x48\x8B\xE9\x48\x85\xD2\x0F\x84"),
            39,
            0x1A0,
            PATCH_IMMEDIATE,
            AY_OBFUSCATE("\x90\x90\x90\x90\x90\x90") // CALL -> NOP NOP NOP NOP NOP NOP
        },
#else
        // offsets for the ConMsgs in this func are
        // 0xC3
        // 0x106
        // 0x12D
        // 0x1A6
        //
        // name:gigalib-patch-CNetChan::CreateFragmentsFromFile-win32
        // Signature for FUN_101a4f90
        // 55 8b ec 83 ec 0c 53 8b 5d 08 8b d1 89 55 f4 56 57
        {
            AY_OBFUSCATE("\x55\x8B\xEC\x83\xEC\x0C\x53\x8B\x5D\x08\x8B\xD1\x89\x55\xF4\x56\x57"),
            17,
            0xC3,
            PATCH_IMMEDIATE,
            AY_OBFUSCATE("\x90\x90\x90\x90\x90\x90") // CALL -> NOP NOP NOP NOP NOP NOP
        },
        {
            AY_OBFUSCATE("\x55\x8B\xEC\x83\xEC\x0C\x53\x8B\x5D\x08\x8B\xD1\x89\x55\xF4\x56\x57"),
            17,
            0x106,
            PATCH_IMMEDIATE,
            AY_OBFUSCATE("\x90\x90\x90\x90\x90\x90") // CALL -> NOP NOP NOP NOP NOP NOP
        },
        {
            AY_OBFUSCATE("\x55\x8B\xEC\x83\xEC\x0C\x53\x8B\x5D\x08\x8B\xD1\x89\x55\xF4\x56\x57"),
            17,
            0x12D,
            PATCH_IMMEDIATE,
            AY_OBFUSCATE("\x90\x90\x90\x90\x90\x90") // CALL -> NOP NOP NOP NOP NOP NOP
        },
        {
            AY_OBFUSCATE("\x55\x8B\xEC\x83\xEC\x0C\x53\x8B\x5D\x08\x8B\xD1\x89\x55\xF4\x56\x57"),
            17,
            0x1A6,
            PATCH_IMMEDIATE,
            AY_OBFUSCATE("\x90\x90\x90\x90\x90\x90") // CALL -> NOP NOP NOP NOP NOP NOP
        },
#endif
        #else
        // Client only!
        /*
            Patch:
            Prevent the culling of skyboxes at high FOVs
        */
        // name:gigalib-patch-R_DrawSkybox-win32
        // Signature for sub_100ECF90 (branch previous2021: 0x10106EA0)
        // 55 8B EC 81 EC 54 02 00 00 8B 0D ? ? ? ?
        // Uniqueish string: R_DrawSkybox
        // 
        // --- 64bit ---
        // name:gigalib-patch-R_DrawSkybox-win64
        // Signature for FUN_1800e92d0
        // 48 8b c4 55 53 41 54 41 55 48 8d a8 f8 fc ff ff 48 81 ec e8 03 00 00 33 db
        // 
        //
        // if ( (((v6 * *&dword_103C0274) + (v7 * *&dword_103C0278)) + (v8 * *&dword_103C027C)) >= -0.29289001 )
        // ->
        // if ( (((v6 * *&dword_103C0274) + (v7 * *&dword_103C0278)) + (v8 * *&dword_103C027C)) >= -1.0 )
        //
        // R_DrawSkyBox
#if PLATFORM_64BITS
        {
            AY_OBFUSCATE("\x48\x8B\xC4\x55\x53\x41\x54\x41\x55\x48\x8D\xA8\xF8\xFC\xFF\xFF\x48\x81\xEC\xE8\x03\x00\x00\x33\xDB"),
            25,
            0x282, // instruction at 0x1800e954e + 4 bytes
            PATCH_REFERENCE, // we are changing the value of a float**
            -1.0f
        },
#else
        {
            AY_OBFUSCATE("\x55\x8B\xEC\x81\xEC\x58\x02\x00\x00\x8B\x0D\x2A\x2A\x2A\x2A\x33\xD2"),
            17,
            0x278,
            PATCH_REFERENCE, // we are changing the value of a float**
            -1.0f
        },
#endif
        // Unclamp mat_picmip
        // Multiple patches are required since the new engine is comparing a pointer (current value?)
        // to the raw, non-negative values. so we just replace the values that it's comparing the pointer to.
        // 
        // name:gigalib-patch-Unclamp-mat_picmip-win32
        // Signature for sub_10184f30 (branch previous2021: 101A4B70)
        // 55 8b ec 83 ec 20 8b ?? ?? ?? ?? ?? 33 d2 53 33 db
        // \x55\x8B\xEC\x83\xEC\x20\x8B\x2A\x2A\x2A\x2A\x2A\x33\xD2\x53\x33\xDB
        //
        // name:gigalib-patch-Unclamp-mat_picmip-win64
        // Signature for FUN_1801A5C80 (64bit)
        // 4c 8b dc 49 89 5b 18 49 89 6b 20 56 57 41 54 41 56 41 57 48 83 ec 50 48 8b 05 ?? ?? ?? ?? 4c 8d 25 ?? ?? ?? ??
        // \x4C\x8B\xDC\x49\x89\x5B\x18\x49\x89\x6B\x20\x56\x57\x41\x54\x41\x56\x41\x57\x48\x83\xEC\x50\x48\x8B\x05\x2A\x2A\x2A\x2A\x4C\x8D\x25\x2A\x2A\x2A\x2A
#if PLATFORM_64BITS
        {
            AY_OBFUSCATE("\x4C\x8B\xDC\x49\x89\x5B\x18\x49\x89\x6B\x20\x56\x57\x41\x54\x41\x56\x41\x57\x48\x83\xEC\x50\x48\x8B\x05\x2A\x2A\x2A\x2A\x4C\x8D\x25\x2A\x2A\x2A\x2A"),
            37,
            0xC9, // instruction at address 0x1801a5d43 + 0x6
            PATCH_IMMEDIATE,
            AY_OBFUSCATE("\x0A")
        },
        {
            AY_OBFUSCATE("\x4C\x8B\xDC\x49\x89\x5B\x18\x49\x89\x6B\x20\x56\x57\x41\x54\x41\x56\x41\x57\x48\x83\xEC\x50\x48\x8B\x05\x2A\x2A\x2A\x2A\x4C\x8D\x25\x2A\x2A\x2A\x2A"),
            37,
            0xD2, // instruction at address 0x1801a5d4c + 0x6
            PATCH_IMMEDIATE,
            AY_OBFUSCATE("\x0A")
        },
#else
        {
            AY_OBFUSCATE("\x55\x8B\xEC\x83\xEC\x20\x8B\x2A\x2A\x2A\x2A\x2A\x33\xD2\x53\x33\xDB"),
            17,
            0x92,
            PATCH_IMMEDIATE,
            AY_OBFUSCATE("\x0A")
        },
        {
            AY_OBFUSCATE("\x55\x8B\xEC\x83\xEC\x20\x8B\x2A\x2A\x2A\x2A\x2A\x33\xD2\x53\x33\xDB"),
            17,
            0x9E,
            PATCH_IMMEDIATE,
            AY_OBFUSCATE("\x0A")
        },
#endif
        // rootlod callback (?) 
        // search for "Root LOD" then the last parameter in the first function
        // that was called, would be the function that we are looking for.
        // 
        // name:gigalib-patch-rootlod-callback-win32
        // Signature for sub_100f3ea0: (branch previous2021: 0x1010dcc0)
        // 55 8B EC 83 EC 08 6A 02
        // \x55\x8B\xEC\x83\xEC\x08\x6A\x02
        //
        // name:gigalib-patch-rootlod-callback-win64
        // Signature for FUN_1800F1210 (64bits)
        // 48 89 5c 24 10 57 48 83 ec 30 48 8b da 48 8b f9 33 d2
        // \x48\x89\x5C\x24\x10\x57\x48\x83\xEC\x30\x48\x8B\xDA\x48\x8B\xF9\x33\xD2
#if PLATFORM_64BITS
        {
            AY_OBFUSCATE("\x48\x89\x5C\x24\x10\x57\x48\x83\xEC\x30\x48\x8B\xDA\x48\x8B\xF9\x33\xD2"),
            18,
            0x6,
            PATCH_IMMEDIATE,
            AY_OBFUSCATE("\x6A\x06\x6A\xF0")
        },
#else
        {
            AY_OBFUSCATE("\x55\x8B\xEC\x83\xEC\x0C\x6A\x02\x6A\x00"),
            8,
            0x6,
            PATCH_IMMEDIATE,
            AY_OBFUSCATE("\x6A\x06\x6A\xF0")
        },
#endif

// disabled for 64bit since the function content has changed so much between the 32bit and 64bit
// builds that I actually can't find a way to make the range from -16 to 6, and -16 to 10, and
// that i don't think there is enough space since RDX XORs itself to make it zero :/
// -kate 22nd Mar 2025
//
// Signature for FUN_1800f1210 (64bit) - referenced by LAB_180007160 (length: 58)
// 48 89 5c 24 10 57 48 83 ec 30 48 8b da 48 8b f9 33 d2 48 8d 0d ?? ?? ?? ?? 44 8d 42 02 e8 ?? ?? ?? ?? 84 c0 0f 85 ?? ?? ?? ?? 48 8b 0d ?? ?? ?? ?? 33 d2 44 8b 05 ?? ?? ?? ??
// \x48\x89\x5C\x24\x10\x57\x48\x83\xEC\x30\x48\x8B\xDA\x48\x8B\xF9\x33\xD2\x48\x8D\x0D\x2A\x2A\x2A\x2A\x44\x8D\x42\x02\xE8\x2A\x2A\x2A\x2A\x84\xC0\x0F\x85\x2A\x2A\x2A\x2A\x48\x8B\x0D\x2A\x2A\x2A\x2A\x33\xD2\x44\x8B\x05\x2A\x2A\x2A\x2A
/*
                             **************************************************************
                             *                          FUNCTION                          *
                             **************************************************************
                             undefined __fastcall FUN_1800f1210(undefined * * param_1, longlong param_2)
             undefined         <UNASSIGNED>   <RETURN>
             undefined * *     RCX:8          param_1
             longlong          RDX:8          param_2
             undefined8        Stack[0x10]:8  local_res10                             XREF[2]:     1800f1210(W),
                                                                                                   1800f12ca(R)
             undefined8        Stack[0x8]:8   local_res8                              XREF[2]:     1800f124a(W),
                                                                                                   1800f12c5(R)
             undefined8        Stack[-0x10]:8 local_10                                XREF[1]:     1800f1276(R)
             undefined1        Stack[-0x18]:1 local_18                                XREF[1]:     1800f125b(*)
                             FUN_1800f1210                                   XREF[5]:     18000716c(*), 180007173(*),
                                                                                          180434f50(*), 180434f60(*),
                                                                                          1807c0050(*)
       1800f1210 48 89 5c        MOV        qword ptr [RSP + local_res10],RBX
                 24 10
       1800f1215 57              PUSH       RDI
       1800f1216 48 83 ec 30     SUB        RSP,0x30
       1800f121a 48 8b da        MOV        RBX,param_2
       1800f121d 48 8b f9        MOV        RDI,param_1
       1800f1220 33 d2           XOR        param_2,param_2
       1800f1222 48 8d 0d        LEA        param_1,[DAT_18069b2a0]
                 77 a0 5a 00
       1800f1229 44 8d 42 02     LEA        R8D,[param_2 + 0x2]
       1800f122d e8 7e df        CALL       FUN_18019f1b0
                 0a 00
       1800f1232 84 c0           TEST       AL,AL
       1800f1234 0f 85 90        JNZ        LAB_1800f12ca
                 00 00 00
       1800f123a 48 8b 0d        MOV        param_1,qword ptr [DAT_1807a7b30]
                 ef 68 6b 00
       1800f1241 33 d2           XOR        param_2,param_2
       1800f1243 44 8b 05        MOV        R8D,dword ptr [DAT_18075008c]
                 42 ee 65 00
*/
#if !PLATFORM_64BITS
        // rootlod
        // name:gigalib-patch-rootlod-win32
        // Signature for sub_100F12B0: (branch previous2021: 0x101083f0)
        // 6A 02 6A 00 68 ? ? ? ? E8 ? ? ? ? 83 C4 0C C3
        {
            AY_OBFUSCATE("\x6A\x02\x6A\x00\x68\x2A\x2A\x2A\x2A\xE8\x2A\x2A\x2A\x2A\x83\xC4\x0C\xC3"),
            18,
            0x0,
            PATCH_IMMEDIATE,
            AY_OBFUSCATE("\x6A\x06\x6A\xF0")
        },

        // lod
        // name:gigalib-patch-lod-win32
        // Signature for sub_100F1290: (previous2021: 100F1E40)
        // 6a 02 6a ff 68 ?? ?? ?? ?? e8 ?? ?? ?? ?? 83 c4 0c c3
        // \x6A\x02\x6A\xFF\x68\x2A\x2A\x2A\x2A\xE8\x2A\x2A\x2A\x2A\x83\xC4\x0C\xC3
        {
            AY_OBFUSCATE("\x6A\x02\x6A\xFF\x68\x2A\x2A\x2A\x2A\xE8\x2A\x2A\x2A\x2A\x83\xC4\x0C\xC3"),
            18, // 9,
            0x0,
            PATCH_IMMEDIATE,
            AY_OBFUSCATE("\x6A\x0A\x6A\xF0")
        }
#endif

        #endif
    #else 
    // LINUX
        #ifdef GAME_DLL
        // Server only!
        /*
            Patch:
            Prevent clients from lagging out the server by spamming a bunch of invalid *netchan->RequestFile requests
            This lags out the server by spamming messages to console (CALL ConMsg), which is resource intensive, because of course it is
        */
        // --- PART ONE ---
        //
        // latest: FUN_003cc630
        // 55 89 E5 57 56 53 81 EC 1C 01 00 00 8B 75 08 0F B6 05 ?? ?? ?? ?? 84 C0
        // 
        // Unique string: "Download file '%s' %s"
        //
        // CNetChan::HandleUpload(char *, int)
#ifdef PLATFORM_64BITS
        {
            // name:gigalib-patch-CNetChan::HandleUpload-linux64
            // Signature for FUN_0064b3b0:
            // 55 48 89 e5 40 57 40 56 40 55 40 54 48 89 f4 53 48 89 fb 48 81 ec 18 01 00 00 0f b6 05 ?? ?? ?? ?? 84 c0 74 ??
            AY_OBFUSCATE("\x55\x89\xE5\x57\x56\x53\x81\xEC\x1C\x01\x00\x00\x8B\x75\x08\x0F\xB6\x05\x2A\x2A\x2A\x2A\x84\xC0"),
            37,
            0x5B,
            PATCH_IMMEDIATE,
            AY_OBFUSCATE("\x90\x90\x90\x90\x90") // CALL -> NOP NOP NOP NOP NOP
        },
#else
        // name:gigalib-patch-CNetChan::HandleUpload-linux32
        // Signature for FUN_003cc630:
        // 55 89 E5 57 56 53 81 EC 1C 01 00 00 8B 75 08 0F B6 05 ?? ?? ?? ?? 84 C0
        {
            // AY_OBFUSCATE("\x55\x89\xE5\x81\xEC\x48\x01\x00\x00\x80\x3D\x2A\x2A\x2A\x2A\x00"),
            AY_OBFUSCATE("\x55\x89\xE5\x57\x56\x53\x81\xEC\x1C\x01\x00\x00\x8B\x75\x08\x0F\xB6\x05\x2A\x2A\x2A\x2A\x84\xC0"),
            24, // 16,
            0x3F, // 0x60,
            PATCH_IMMEDIATE,
            AY_OBFUSCATE("\x90\x90\x90\x90\x90") // CALL -> NOP NOP NOP NOP NOP
        },
#endif
        // --- PART TWO THREE FOUR AND FIVE---
        //
        // 
        // --- 64bit ---
        // name:gigalib-patch-CNetChan::CreateFragmentsFromFile-linux32
        // Signature for FUN_00646590:
        // 55 48 89 e5 40 57 40 56 40 55 48 89 fd 40 54 48 89 f4 53 89 cb 48 83 ec 28 48 8d 3d ?? ?? ?? ??
        // 
        // offsets for the ConMsgs in this func are
        // 0x19C
        // 0x1BA
        // 0x1D4
        // 0x184
        // 
        // 
        // --- 32bit ---
        // name:gigalib-patch-CNetChan::CreateFragmentsFromFile-linux32
        // Signature for FUN_003c7e10:
        // 55 89 E5 57 89 CF 56 53 89 D3 83 EC 30 89 45 D4 A1 ?? ?? ?? ?? 8D 50 04 8B 40 04
        // \x55\x89\xE5\x57\x89\xCF\x56\x53\x89\xD3\x83\xEC\x30\x89\x45\xD4\xA1\x2A\x2A\x2A\x2A\x8D\x50\x04\x8B\x40\x04
        // 
        // offsets for the ConMsgs in this func are
        // 0x191
        // 0x1DB
        // 0x170
        // 0x1B4
        // 
        // Unique string: "CreateFragmentsFromFile: '%s' doesn't"
        //
        // CNetChan::CreateFragmentsFromFile(char const*, int, unsigned int)
        #ifdef PLATFORM_64BITS
        {
            AY_OBFUSCATE("\x55\x48\x89\xE5\x40\x57\x40\x56\x40\x55\x48\x89\xFD\x40\x54\x48\x89\xF4\x53\x89\xCB\x48\x83\xEC\x28\x48\x8D\x3D\x2A\x2A\x2A\x2A"),
            32, // 15,
            0x19C,
            PATCH_IMMEDIATE,
            AY_OBFUSCATE("\x90\x90\x90\x90\x90") // CALL -> NOP NOP NOP NOP NOP
        },
        {
            AY_OBFUSCATE("\x55\x48\x89\xE5\x40\x57\x40\x56\x40\x55\x48\x89\xFD\x40\x54\x48\x89\xF4\x53\x89\xCB\x48\x83\xEC\x28\x48\x8D\x3D\x2A\x2A\x2A\x2A"),
            32, // 15,
            0x1BA,
            PATCH_IMMEDIATE,
            AY_OBFUSCATE("\x90\x90\x90\x90\x90") // CALL -> NOP NOP NOP NOP NOP
        },
        {
            AY_OBFUSCATE("\x55\x48\x89\xE5\x40\x57\x40\x56\x40\x55\x48\x89\xFD\x40\x54\x48\x89\xF4\x53\x89\xCB\x48\x83\xEC\x28\x48\x8D\x3D\x2A\x2A\x2A\x2A"),
            32, // 15,
            0x1D4,
            PATCH_IMMEDIATE,
            AY_OBFUSCATE("\x90\x90\x90\x90\x90") // CALL -> NOP NOP NOP NOP NOP
        },
        {
            AY_OBFUSCATE("\x55\x48\x89\xE5\x40\x57\x40\x56\x40\x55\x48\x89\xFD\x40\x54\x48\x89\xF4\x53\x89\xCB\x48\x83\xEC\x28\x48\x8D\x3D\x2A\x2A\x2A\x2A"),
            32, // 15,
            0x184,
            PATCH_IMMEDIATE,
            AY_OBFUSCATE("\x90\x90\x90\x90\x90") // CALL -> NOP NOP NOP NOP NOP
        },
        #else
        {
            AY_OBFUSCATE("\x55\x89\xE5\x57\x89\xCF\x56\x53\x89\xD3\x83\xEC\x30\x89\x45\xD4\xA1\x2A\x2A\x2A\x2A\x8D\x50\x04\x8B\x40\x04"),
            27, // 15,
            0x191,
            PATCH_IMMEDIATE,
            AY_OBFUSCATE("\x90\x90\x90\x90\x90") // CALL -> NOP NOP NOP NOP NOP
        },
        {
            AY_OBFUSCATE("\x55\x89\xE5\x57\x89\xCF\x56\x53\x89\xD3\x83\xEC\x30\x89\x45\xD4\xA1\x2A\x2A\x2A\x2A\x8D\x50\x04\x8B\x40\x04"),
            27, // 15,
            0x1DB,
            PATCH_IMMEDIATE,
            AY_OBFUSCATE("\x90\x90\x90\x90\x90") // CALL -> NOP NOP NOP NOP NOP
        },
        {
            AY_OBFUSCATE("\x55\x89\xE5\x57\x89\xCF\x56\x53\x89\xD3\x83\xEC\x30\x89\x45\xD4\xA1\x2A\x2A\x2A\x2A\x8D\x50\x04\x8B\x40\x04"),
            27, // 15,
            0x170,
            PATCH_IMMEDIATE,
            AY_OBFUSCATE("\x90\x90\x90\x90\x90") // CALL -> NOP NOP NOP NOP NOP
        },
        {
            AY_OBFUSCATE("\x55\x89\xE5\x57\x89\xCF\x56\x53\x89\xD3\x83\xEC\x30\x89\x45\xD4\xA1\x2A\x2A\x2A\x2A\x8D\x50\x04\x8B\x40\x04"),
            27, // 15,
            0x1B4,
            PATCH_IMMEDIATE,
            AY_OBFUSCATE("\x90\x90\x90\x90\x90") // CALL -> NOP NOP NOP NOP NOP
        },
        #endif
        #else
        // Client only!
        /*
            Patch:
            Prevent the culling of skyboxes at high FOVs
        */
        //
        // name:gigalib-patch-R_DrawSkybox-linux64
        // Signature for FUN_005471c0: (64bit)
        // 55 31 c0 48 89 e5 40 57 40 56 40 55 40 54 40 89 fc 53 48 81 ec ?? ?? ?? ?? 48 8b 1d ?? ?? ?? ?? f3 0f 11 85 7c fc ff ff 48 c7 85 80 fc ff ff 00 00 00 00
        //
        // name:gigalib-patch-R_DrawSkybox-linux32
        // Signature for FUN_002d4c10: (32bit)
        // 55 66 0F EF C0 89 E5 57 56 53 81 EC 8C 02 00 00 A1 ?? ?? ?? ?? C7 85 80 FD FF FF 00 00 00 00
        // 
        // Uniqueish string: R_DrawSkybox
        //
        // if ( (((v6 * *&dword_B71424) + (v5 * *&dword_B71420)) + (v7 * *&dword_B71428)) < -0.29289001 )
        // ->
        // if ( (((v6 * *&dword_B71424) + (v5 * *&dword_B71420)) + (v7 * *&dword_B71428)) < -1.0 )
        //
        // R_DrawSkyBox
        // search for raw hex "BE95F5AE" and then go to the function that references that data. should be FUN_002d4c10
        // code to replace isn't visible for the 32bit linux binary, but the MOVSS instructions match
        //
        // linux:
        // 002d4e50 f3 0f 59        MULSS    XMM2,dword ptr [DAT_0086115c]    = ??
        //          15 5c 11
        //          86 00
        // 002d4e58 f3 0f 59        MULSS    XMM1,dword ptr [DAT_0061158]     = ??
        //          0d 58 11
        //          86 00
        // 002d4e60 f3 0f 59        MULSS    XMM3,dword ptr [DAT_0061160]     = ??
        //          1d 60 11
        //          86 00
        // 002d4e68 f3 0f 10        MOVSS    XMM7,dword ptr [DAT_0066fac0]    = BE95F5AEh     <<<< HERE
        //          3d c0 fa
        //          66 00
        //
        // windows:
        // 100ed1e4 f3 0f 59        MULSS    XMM0,dword ptr [DAT_103c5d78]
        //          05 78 5d
        //          3c 10
        // 100ed1ec f3 0f 59        MULSS    XMM4,dword ptr [DAT_103c5d74]    = 3F800000h
        //          25 74 5d
        //          3c 10
        // 100ed1f4 f3 0f 59        MULSS    XMM1,dword ptr [DAT_103c5d7c]
        //          0d 7c 5d
        //          3c 10
        // 100ed1fc f3 0f 58 c4     ADDSS    XMM0,XMM4
        // 100ed200 f3 0f 58 c1     ADDSS    XMM0,XMM1
        // 100ed204 f3 0f 10        MOVSS    XMM1,dword ptr [DAT_10309280]    = BE95F5AEh     <<<< HERE
        //          0d 80 92
        //          30 10
        // 100ed20c 0f 2f c8        COMISS   XMM1,XMM0
        // 100ed20f 0f 87 51        JA       LAB_100ed666
        //          04 00 00
        #ifdef PLATFORM_64BITS
        {
            AY_OBFUSCATE("\x55\x31\xC0\x48\x89\xE5\x40\x57\x40\x56\x40\x55\x40\x54\x40\x89\xFC\x53\x48\x81\xEC\x2A\x2A\x2A\x2A\x48\x8B\x1D\x2A\x2A\x2A\x2A\xF3\x0F\x11\x85\x7C\xFC\xFF\xFF\x48\xC7\x85\x80\xFC\xFF\xFF\x00\x00\x00\x00"),
            51,
            0x27B,
            PATCH_REFERENCE, // we are changing the value of a float**
            -1.0f
        },
        #else
        {
            AY_OBFUSCATE("\x55\x66\x0F\xEF\xC0\x89\xE5\x57\x56\x53\x81\xEC\x8C\x02\x00\x00\xA1\x2A\x2A\x2A\x2A\xC7\x85\x80\xFD\xFF\xFF\x00\x00\x00\x00"),
            31, // 19,
            0x25C, // 0x424,
            PATCH_REFERENCE, // we are changing the value of a float**
            -1.0f
        },
        #endif
        #endif
    #endif
};


#include <fakeconvar.h>
void CBinary::PostInit()
{
    // Only run this on dedicated servers, not on clients
    #ifdef GAME_DLL
        if (engine->IsDedicatedServer())
        {
            bool didpatches = ApplyAllPatches();

            if (!didpatches)
            {
                #ifdef dbging
                    Warning("CEngineBinary::EPostInit -> Failed to apply server patches!\n");
                #else
                    Error("Failed to apply server patches!\n");
                    return;
                #endif
            }
            #ifdef dbging
            else
            {
                ConColorMsg(goodcolor, "CEngineBinary::EPostInit -> Successfully applied server patches!\n");
            }
            #endif
        }
    #else
        bool didpatches = ApplyAllPatches();

        if (!didpatches)
        {
            #ifdef dbging
                Warning("CEngineBinary::EPostInit -> Failed to apply client patches!\n");
            #else
                Error("Failed to apply client patches!\n");
                return;
            #endif
        }
        #ifdef dbging
        else
        {
            ConColorMsg(goodcolor, "CEngineBinary::EPostInit -> Successfully applied client patches!\n");
        }
        #endif



        // Fully fix the rest of mat_picmip - set in a bin patch we had earlier.
        ConVarRef mat_picmip("mat_picmip");
        ConVarRef r_rootlod("r_rootlod");
        ConVarRef r_lod("r_lod");
        if (mat_picmip.IsValid())
        {
            ConVar*     realVar = static_cast<ConVar*>(mat_picmip.GetLinkedConVar());
            FakeConVar* fakeVar = reinterpret_cast<FakeConVar*>(realVar);
            fakeVar->SetMax(10.0);
            fakeVar->SetMin(-10.0);
        }
        if (r_rootlod.IsValid())
        {
            ConVar* realVar     = static_cast<ConVar*>(r_rootlod.GetLinkedConVar());
            FakeConVar* fakeVar = reinterpret_cast<FakeConVar*>(realVar);
            fakeVar->SetMax(6.0);
            fakeVar->SetMin(-10.0);
        }
        if (r_lod.IsValid())
        {
            ConVar* realVar     = static_cast<ConVar*>(r_lod.GetLinkedConVar());
            FakeConVar* fakeVar = reinterpret_cast<FakeConVar*>(realVar);
            fakeVar->SetMax(10.0);
            fakeVar->SetMin(-10.0);
        }

    #endif

    // now run engine detours
    gCEngineDetours = new CEngineDetours;

    return;
}

bool CBinary::ApplyAllPatches()
{
    // loop thru our engine patches
    for (int i = 0; i < (sizeof(g_EnginePatches) / sizeof(*g_EnginePatches)); i++)
    {
        // if something goes wrong, bail
        if (!g_EnginePatches[i].ApplyPatch(engine_bin))
        {
            #ifdef dbging
                Warning("CEngineBinary::ApplyAllPatches -> Couldn't apply patch %i\n", i);
                continue;
            #else
                return false;
            #endif
            
        }
        else
        {
            #ifdef dbging
                ConColorMsg(goodcolor, "CEngineBinary::ApplyAllPatches -> Applied patch %i\n", i);
            #endif
        }
    }
    return true;
}

bool CBinPatch::ApplyPatch(modbin* mbin)
{
    if (!m_pPatch)
    {
        // No value provided to patch
        #ifdef dbging
            Warning("CBinPatch::ApplyPatch -> No value provided for patch\n");
        #endif

        return false;
    }


    void* addr = (void*)memy::FindPattern(
        mbin->addr,
        mbin->size,
        m_pSignature,
        m_iSize,
        m_iOffset
    );

    if (addr)
    {
        void* pMemory = m_bImmediate ? (uintptr_t*)addr : *reinterpret_cast<uintptr_t**>(addr);

        // Memory is write-protected so it needs to be lifted before the patch is applied
        int prot = NULL;
        if (memy::SetMemoryProtection(pMemory, m_iPatchLength, MEM_READ | MEM_WRITE | MEM_EXEC, &prot))
        {
            V_memcpy(pMemory, m_pPatch.get(), m_iPatchLength);

            int _ = 0;
#ifdef PLATFORM_WINDOWS
            memy::SetMemoryProtection(pMemory, m_iPatchLength, prot, &_);
#else
            memy::SetMemoryProtection(pMemory, m_iPatchLength, MEM_READ | MEM_EXEC, &_);
#endif
            // Success!
            return true;
        }
        else
        {
            #ifdef dbging
                Warning("CBinPatch::ApplyPatch -> Couldn't override mem protection for pattern %s, size %i, offs %i\n", m_pSignature, m_iSize, m_iOffset);
            #endif

            return false;
        }
    }
    else
    {
        // Couldn't find sig
        #ifdef dbging
            Warning("CBinPatch::ApplyPatch -> Couldn't find sig for pattern %s, size %i, offs %i\n", m_pSignature, m_iSize, m_iOffset);
        #endif
        return false;
    }
}

CBinPatch::CBinPatch(char* signature, size_t sigsize, size_t offset, bool immediate)
{
    m_pSignature    = signature;
    m_iSize         = sigsize,
    m_iOffset       = offset;
    m_bImmediate    = immediate;
    m_pPatch        = nullptr;
    m_iPatchLength  = 0;
}

CBinPatch::~CBinPatch()
{
}


// Converting numeric types into bytes
CBinPatch:: CBinPatch(char* signature, size_t sigsize, size_t offset, bool immediate, int value)
    :       CBinPatch(signature, sigsize, offset, immediate)
{
    m_iPatchLength = sizeof(value);
    m_pPatch = std::make_unique<char>( m_iPatchLength );
    memcpy(m_pPatch.get(), &value, m_iPatchLength);
}

CBinPatch:: CBinPatch(char* signature, size_t sigsize, size_t offset, bool immediate, float value)
    :       CBinPatch(signature, sigsize, offset, immediate)
{
    m_iPatchLength = sizeof(value);
    m_pPatch = std::make_unique<char>(m_iPatchLength);
    memcpy(m_pPatch.get(), &value, m_iPatchLength);
}


// BUGBUG!!!!
// SIZEOF ISN'T CORRECT IF YOU HAVE NULL BYTES IN THE PATCH??
CBinPatch:: CBinPatch(char* signature, size_t sigsize, size_t offset, bool immediate, char* bytes)
    :       CBinPatch(signature, sigsize, offset, immediate)
{
    m_iPatchLength = strlen(bytes);
    m_pPatch = std::make_unique<char>(m_iPatchLength);
    memcpy(m_pPatch.get(), bytes, m_iPatchLength);

    #ifdef dbging
        char hexstr[128] = {};
        V_binarytohex
        (
            reinterpret_cast<const byte*>(signature),
            (sigsize * 2),
            hexstr,
            (sigsize * 2)
        );

        Warning("patchlen %s = %i / %i \n", hexstr, sizeof(bytes), strlen(bytes));
    #endif
}
#endif
